### ISSUE TITLE
Improve handling of at-runtime `SteamAudioPlayer` destruction

### ISSUE THREAD

**Issue by stechyo** [stechyo/godot-steam-audio#21]
Deleting a `SteamAudioPlayer` at runtime (by e.g. running queue_free() on a script) may cause the game to crash. There must be improvements to locking on Server::tick() and on the reflection thread in order to reduce that. Something I had tried but didn't work was using `std::unique_lock` on the destructor and `std::shared_lock` on _mix, tick, and the reflection thread, which should make the destructor wait for all shared locks to be unlocked before proceeding to destruction... but that doesn't seem to be working.

**Comment by stechyo** [comment]
Closing this after some testing because of #28, which seems to fix these crashes, along with: 
https://github.com/stechyo/godot-steam-audio/blob/aa97bf0a51ca2088134c60cee6aa7e396e5df890/src/server.cpp#L226C1-L233C4

**Comment by Robert-K** [comment]
Unfortunately, calling `queue_free()` on any `SteamAudioPlayer` node immediately breaks the reflection simulation for me.
SteamAudioPlayers will keep their 'reflection settings', but all newly created one's have no reverb/echo applied to them.

I'll happily share code/projects for reproduction purposes.

**Comment by stechyo** [comment]
Hm not sure if I follow. The two sentences that you wrote seem to be two separate issues. Could you elaborate?

**Comment by Robert-K** [comment]
Sure. Up until the removal of the first SteamAudioPlayer using `queue_free()`, everything works as expected.

After that, newly created SteamAudioPlayers have no reflections and existing SteamAudioPlayers' reflections don't change when they're moved.

It seems like the reflection sim crashes.
