### ISSUE TITLE
SteamAudioPlayer will not play if sub_steam is set via code

### ISSUE THREAD

**Issue by shaunzorr** [stechyo/godot-steam-audio#25]
Hello,

I've made up a test project to demonstrate this issue here - https://github.com/shaunzorr/test_steamaudio_godot

If the sub_stream is not set in the editor and is set via code the SteamAudioPlayer will not play using the play() method.

no console errors.

**Comment by stechyo** [comment]
Opened #26 for this, I probably won't make a release just for this fix but here's a custom release if you want to check that it works yourself.
[godot-steam-audio-vX.Y.Z.zip](https://github.com/stechyo/godot-steam-audio/files/13919470/godot-steam-audio-vX.Y.Z.zip)
