### ISSUE TITLE
Add CI build action

### ISSUE THREAD

**Issue by stechyo** [stechyo/godot-steam-audio#31]
Getting a build of the extension for every commit would be nice, esp. for letting other people test things before a release is out.

**Comment by Ughuuu** [comment]
https://github.com/godotengine/godot-cpp-template?tab=readme-ov-file#usage---actions
I could give it a try if you want.

**Comment by stechyo** [comment]
Oh, thanks but I'm already on it. 
https://github.com/stechyo/godot-steam-audio/actions/runs/8582500899

**Comment by Ughuuu** [comment]
You could take a look into the one i linked, that builds for all oses and signs mac build.

**Comment by Ughuuu** [comment]
Advantage with that is that when you want to do a release, you can reuse those artifacts and directly make release. And you would have reproducible builds.

**Comment by stechyo** [comment]
Right now I’m just building for Linux/Windows x64. Doesn’t Mac signing require you to fork over some money annually to Apple? 

The current action generates artifacts in the same way as previous releases of this extension, which looks good enough to me, but it would be cool to make a per-OS split and save people some bandwidth.

**Comment by Ughuuu** [comment]
I see, so you don't have an apple dev account. Then y, signing won't be possible using this repo. It would still be cool to build it, and then people need to click a popup and it would still run.
And am assuming web/mobile/ios also aren't targeted?

**Comment by Ughuuu** [comment]
> Right now I’m just building for Linux/Windows x64. Doesn’t Mac signing require you to fork over some money annually to Apple?
> 
> The current action generates artifacts in the same way as previous releases of this extension, which looks good enough to me, but it would be cool to make a per-OS split and save people some bandwidth.

Not sure that would be needed, usually people would download the whole package with everything.

**Comment by stechyo** [comment]
With regards to other platforms:
 - web isn't supported by steam-audio
 - iOS runs into the same issue as macOS I imagine
 - Android might work, I'm just not supporting it (as in, I don't really test new releases on Android), so I'm not including binaries for that in the official release. If anyone starts opening issues on Android I'll look into it.
