### ISSUE TITLE
Disable Ambisonics toggle option

### ISSUE THREAD

**Issue by stechyo** [stechyo/godot-steam-audio#32]
Users may not be interested in rendering more than 2 channels of audio, and may prefer to disable ambisonics and enable the built-in spatial panning.

**Comment by levidavidmurray** [comment]
What do you mean by "built-in panning"? Are you referring to Godot's built-in spatial panning (would this even work?) or applying the [binaural effect](https://valvesoftware.github.io/steam-audio/doc/capi/guide.html#binaural-effect) as opposed to ambisonics?

**Comment by stechyo** [comment]
Yeah, referring to Godot’s spatial panning. I still have to try it but I’m probably gonna close this one, because what’s likely to happen is that Godot applies panning to reflections, which kind of breaks the reverb effect.

(We could also add a normal SteamAudio binaural effect that doesn’t involve Ambisonics, that probably burns through less CPU and does what I’d guess most of our users want.)

**Comment by levidavidmurray** [comment]
Is disabling ambisonics even supported right now? The option exists on `SteamAudioPlayer`, but the results...

(I had to lower the video audio when ambisonics are disabled. The first time scared the hell outta me, and it seems to get progressively louder)

https://github.com/stechyo/godot-steam-audio/assets/46084870/f1d4f85c-f287-4525-a2d2-62bf507be75a

**Comment by stechyo** [comment]
Yeah I'd forgotten how disabled Ambisonics sounds. (Working with audio in programming regularly must cause hearing damage.) After checking `phonon.h` it seems that the binaural effect doesn't support rotation (you can only provide a direction from listener to source on its params, not a listener transform, so there is no data for rotating audio), so I'd actually just change this issue to disabling the Ambisonics toggle option.
