### ISSUE TITLE
Investigate some way of auto-importing meshes from Blender as SteamAudioGeometries

### ISSUE THREAD

**Issue by stechyo** [stechyo/godot-steam-audio#41]
Godot supports import hints for turning meshes into colliders (see [here](https://docs.godotengine.org/en/4.1/tutorials/assets_pipeline/importing_scenes.html#create-collisions-col-convcol-colonly-convcolonly)). It could be interesting to have something like that but to mark meshes as steam-audio geometries. 

([Relevant doc](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/import_plugins.html#))

**Comment by cwook** [comment]
As a workaround, you can use an import script to add a SteamAudioGeometry to each MeshInstance node.

```gdscript
@tool
extends EditorScenePostImport

var root : Node
func _post_import(scene):
	root = scene
	iterate(scene)
	return scene

func iterate(node):
	if node != null and node is MeshInstance3D:
		var sag := SteamAudioGeometry.new()
		node.add_child(sag)
		# make the SteamAudioGeometry visible in the editor hierachy (optional)
		sag.owner = root
		# add a default SteamAudioMaterial (the defaults are all 0 otherwise and sound weird)
		sag.material = preload("res://Art/Sound/AudioMaterials/SteamAudioMaterial.tres")
		for child in node.get_children():
			iterate(child)

```

**Comment by fire** [comment]
What is needed?

**Comment by stechyo** [comment]
What’s described in the OP really. This sounded like an interesting idea but I confess I haven’t actually tried import hints myself yet.
