### ISSUE TITLE
Clarify SteamAudio license in README

### ISSUE THREAD

**Issue by davidak** [stechyo/godot-steam-audio#42]
My first question when seeing this was what [steam-audio](https://github.com/ValveSoftware/steam-audio) is and if it's open source.

The [website](https://valvesoftware.github.io/steam-audio/) explains what it is and the [license](https://github.com/ValveSoftware/steam-audio/blob/master/LICENSE.md) says it's proprietary.

It would be good to clarify that in the README and suggest interested users to upvote the [issue](https://github.com/ValveSoftware/steam-audio/issues/2) which asks to release it as open source.

Would you accept a pull requests with such changes?

Thanks for your work on this extension!

**Comment by stechyo** [comment]
Hi, thanks for the issue! Please review #43.

**Comment by davidak** [comment]
It was released as open source (Apache-2.0 license) 9 hours ago! :open_mouth: 

https://github.com/ValveSoftware/steam-audio/commit/2b00778afdae7419da838347a9bd0545ed59dd25
https://steamcommunity.com/games/596420/announcements/detail/7745698166044243233
