### ISSUE TITLE
steam-audio is now apache 2!

### ISSUE THREAD

**Issue by fire** [stechyo/godot-steam-audio#44]
https://github.com/ValveSoftware/steam-audio/

**Comment by stechyo** [comment]
Oh this is awesome! It will definitely help me debug some stuff. I’ll update the README and close this issue when I get the chance, thanks!

**Comment by duplexsystem** [comment]
@stechyo The precompiled binaries are not fully open source. They include intel ipp which is a closed source library. In order to have open source steam audio binaries you must build them from source without closed source libraries.

**Comment by stechyo** [comment]
...yeah, I noticed this when I was checking the build instructions for SteamAudio today. I'll make a note in the README. Thanks!
