### ISSUE TITLE
Suggestion: Editor importing with automatic SteamAudioGeometry

### ISSUE THREAD

**Issue by mrjshzk** [stechyo/godot-steam-audio#47]
I know this is not your focus, but let's say I have have hundreds of GLB/FBX files and normally, I just open them by clicking on them twice, opening the new import tab, where you can add static/dynamic colliders to the meshes and whatnot. I was wondering if it would be able to have something like this in the new import tab where you can add a SteamAudioGeometry without having to make a new inherited scene! Thanks!

**Comment by mrjshzk** [comment]
![Untitled-1](https://github.com/stechyo/godot-steam-audio/assets/115943663/450736b0-10af-4a58-9134-b10923bdad5c)
Something like this. Don't know if the Godot importing API can be used this way, but I think it would be very useful. In the couple days I'll investigate if this is possible.

**Comment by stechyo** [comment]
Hi, I don't think I can extend the import dialogue window, but with #51 you can name the objects with "-sadg" or "-sasg" at the end (depending on whether you want dynamic or static geometry), much like the [import hints](https://docs.godotengine.org/en/4.1/tutorials/assets_pipeline/importing_scenes.html#import-hints) already present in Godot, and it will generate geometry for you as long as you set the post-import script on your GLTF scene to addons/godot-steam-audio/src/post_import.gd .

**Comment by mrjshzk** [comment]
Awesome, thanks!
