### ISSUE TITLE
Integrating with GodotSteam voice functionality

### ISSUE THREAD

**Issue by ismailivanov** [stechyo/godot-steam-audio#59]
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/20d14040-f3b2-4e65-92fd-e8df5f4e1cd9)
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/1ff9994d-c98e-460a-a30f-6f13cdf79107)

1,: SteamAudioStream mix_rate variable is missing. 
2: 'SteamAudioStreamPlayback' has no function 'get_frames_available'.

**Comment by ismailivanov** [comment]
Are you still working on the plugin?

**Comment by stechyo** [comment]
Hi, neither mix_rate or get_frames_available are methods/fields in either SteamAudioStream/Playback or AudioStream/Playback (the built-in classes that are inherited by this extension.

**Comment by ismailivanov** [comment]
> Hi, neither mix_rate or get_frames_available are methods/fields in either SteamAudioStream/Playback or AudioStream/Playback (the built-in classes that are inherited by this extension.

But i dont understand how to implement with Steam Voice system. **https://godotsteam.com/tutorials/voice/**

**Comment by stechyo** [comment]
I’m not familiar with this Steam Voice plugin, but generally you’ll want to just assign the voice output stream to a SteamAudioPlayer.

**Comment by ismailivanov** [comment]
> I’m not familiar with this Steam Voice plugin, but generally you’ll want to just assign the voice output stream to a 

![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/b86e2051-b916-4864-acb0-9289b0370285)
I'm having trouble with AudioStreamGeneratorPlayback. I have no idea how to do this, I guess we can't get Playback from AudioStreamGenerator. I think you can only get playback from AudioStreamPlayer, but when I call get_stream_playback() from SteamAudioPlayer, it returns SteamAudioStreamPlayback. There are no methods like get_frames_available() in SteamAudioStreamPlayback.

**Comment by stechyo** [comment]
So you need to access the AudioStreamGeneratorPlayback when it's being played, is that it? There's no way to do this currently, you only have `get_inner_stream` on SteamAudioPlayer but no `get_inner_stream_playback`. I'll see if I can add this on a PR today. 

A side note: 
```gdscript
local_playback = streamplay.instantiate_playback()
```
You probably don't want to use this function at all. `instantiate_playback` is called by the audio player when it starts playing, you're just creating another playback which will not have the data you need.

**Comment by ismailivanov** [comment]
> So you need to access the AudioStreamGeneratorPlayback when it's being played, is that it? There's no way to do this currently, you only have on SteamAudioPlayer but no . I'll see if I can add this on a PR today.`get_inner_stream``get_inner_stream_playback`
> 
> A side note:
> 
> ```gdscript
> local_playback = streamplay.instantiate_playback()
> ```
> 
> You probably don't want to use this function at all. is called by the audio player when it starts playing, you're just creating another playback which will not have the data you need.`instantiate_playback`

I'd appreciate it if you could add the feature. I'm on hold. Thanks.

**Comment by stechyo** [comment]
#60 should fix it, let it build a release and then you should be able to try the new function and see if it works for your use case.

**Comment by stechyo** [comment]
Let me know if this gets fixed with [this release](https://github.com/stechyo/godot-steam-audio/actions/runs/9470308879/artifacts/1590842799).

**Comment by ismailivanov** [comment]
> Let me know if this gets fixed with [this release](https://github.com/stechyo/godot-steam-audio/actions/runs/9470308879/artifacts/1590842799).

![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/1690825a-10c5-451e-aa11-042282fbe536)
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/b0f7dd33-66f3-4386-b242-cd47e98028c6)

**Comment by stechyo** [comment]
The playback might be null in the same frame where you `play_stream()`. What happens if you add local_playback != null to that if statement?

**Comment by ismailivanov** [comment]
> The playback might be null in the same frame where you `play_stream()`. What happens if you add local_playback != null to that if statement?


Its returning always null

And this error

![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/84c83cf9-e17e-4206-84ef-ae570764f3c5)

**Comment by stechyo** [comment]
Can I get a decent text snippet of your code? It's hard to guess what's happening with a bunch of print-screens.

**Comment by ismailivanov** [comment]
> Can I get a decent text snippet of your code? It's hard to guess what's happening with a bunch of print-screens.

[Voice.zip](https://github.com/user-attachments/files/15793424/Voice.zip)

Warning
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/767dc00b-1af1-4c89-bbcb-ed6f1f171237)

Error
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/85fe0867-eac7-44a4-ab1b-c3a9a92b8941)

**Comment by stechyo** [comment]
Is the inner stream already set in `_ready()`? The problem seems to be that `play()` is doing nothing, either because no stream is set either on the editor or by using `play_stream()`. The player turns inactive immediately, which means that you don't have an inner playback (and that's what that warning is telling you).

**Comment by ismailivanov** [comment]
> Is the inner stream already set in `_ready()`? The problem seems to be that `play()` is doing nothing, either because no stream is set either on the editor or by using `play_stream()`. The player turns inactive immediately, which means that you don't have an inner playback (and that's what that warning is telling you).

I don't know anything about audio, I followed the documentation completely and now I am doing the same as in the documentation, but it still returns empty value get_inner_stream_playback.

Here is the documantation
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/ab7ef189-b1e1-4669-a5f1-c825a85471e5)

And here is the my code
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/cb17e7d5-ff2b-4529-8f8d-4bc043cfd05c)
`NOTE: I tried also audio_node.play_stream(audio_node.get_inner_stream)`

![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/fb459935-7047-4f18-a520-d3252ff3e026)

**Comment by stechyo** [comment]
A question: have you made GodotSteam voice work _in isolation_?

**Comment by ismailivanov** [comment]
> A question: have you made GodotSteam voice work _in isolation_?

What is isolation

If you're asking if it works without SteamAudio, yes, it worked before.

**Comment by stechyo** [comment]
Alright, good. Well, this is weird because, in theory, your issue is that no sound is playing. What happens if you
```gdscript
print(audio_node.is_playing())
```
right after line 31?

And what happens if you assign `local_playback` on `_process` rather than on `_ready`?

**Comment by ismailivanov** [comment]
> Alright, good. Well, this is weird because, in theory, your issue is that no sound is playing. What happens if you
> 
> ```gdscript
> print(audio_node.is_playing())
> ```
> 
> right after line 31?
> 
> And what happens if you assign `local_playback` on `_process` rather than on `_ready`?

1:Its returning false


2: Same Warning and Error every frame

**Comment by stechyo** [comment]
What about `print(audio_node.is_playing())` on _process() ?

**Comment by ismailivanov** [comment]
> print(audio_node.is_playing())

Always false

**Comment by stechyo** [comment]
That means audio is not playing at all, which doesn't seem to have anything to do with this extension.

**Comment by ismailivanov** [comment]
> That means audio is not playing at all, which doesn't seem to have anything to do with this extension.

https://github.com/stechyo/godot-steam-audio/assets/64804972/fed3c5ae-dd5b-485d-8106-ff18e49b5da8

This is without SteamAudio
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/48d097f8-c518-432d-8571-fcc1c55aef57)

**Comment by stechyo** [comment]
This is with a regular AudioStreamPlayer3d I take it? At this point I need a minimal reproduction project, I am not familiar with GodotSteam and I don't have enough context to be of any help.

**Comment by ismailivanov** [comment]
> This is with a regular AudioStreamPlayer3d I take it? At this point I need a minimal reproduction project, I am not familiar with GodotSteam and I don't have enough context to be of any help.

Here is the minimal reproduction project
[project](https://www.mediafire.com/file/0lwe1tg7feck7vd/MinimalReproductionSteamVoiceSteamAudio.zip/file )
If you set the node to AudioStreamPlayer3D but no sound is heard. Your microphone is not selected in Windows.

**Comment by stechyo** [comment]
Try completely removing this addon and installing it again. Your project has something that's clearly wrong in the bin folder, since removing it and reinstalling makes `get_inner_stream_playback` return things.

**Comment by ismailivanov** [comment]
> Try completely removing this addon and installing it again. Your project has something that's clearly wrong in the bin folder, since removing it and reinstalling makes `get_inner_stream_playback` return things.

I tried it in the demo you made and now all sounds is not working. 
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/d17f1eff-84ac-4089-a645-74cc0e8a09db)

**Comment by ismailivanov** [comment]
> > Try completely removing this addon and installing it again. Your project has something that's clearly wrong in the bin folder, since removing it and reinstalling makes `get_inner_stream_playback` return things.
> 
> I tried it in the demo you made and now all sounds is not working. ![image](https://private-user-images.githubusercontent.com/64804972/338727343-d17f1eff-84ac-4089-a645-74cc0e8a09db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzU4OTAsIm5iZiI6MTcxODEzNTU5MCwicGF0aCI6Ii82NDgwNDk3Mi8zMzg3MjczNDMtZDE3ZjFlZmYtODRhYy00MDg5LWE2NDUtNzRjYzBlOGEwOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE5NTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWY0ZGM0NTFiMjljNGM2MjE5ZGU5MDQwMDQyZmIyMTE5MWMxZjgyOTY0MjQwYjAwMjM0NzRlMWY2ODU5NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjtJiPMGMkAQvD65qmmDlRVuYfVaHOItWNqDdlJkfBo)

Game is working but no sound

**Comment by stechyo** [comment]
Is there anything below those logs? Ignore "appears to be already registered".

**Comment by ismailivanov** [comment]
> Is there anything below those logs? Ignore "appears to be already registered".

![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/eda54b9e-a8a7-4b60-bcae-5e47b5cd9536)

**Comment by stechyo** [comment]
Well, if the demo doesn't work I'd say you're not properly installing the extension. Please refer to [the wiki](https://github.com/stechyo/godot-steam-audio/wiki/Installation).

**Comment by ismailivanov** [comment]
> Well, if the demo doesn't work I'd say you're not properly installing the extension. Please refer to [the wiki](https://github.com/stechyo/godot-steam-audio/wiki/Installation).

Demo was working . When i changed with new PR is not working.
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/ea79d36c-78fe-4e03-977f-96b6c05988a7)

**Comment by stechyo** [comment]
Why is there a `godot-steam-audio` folder inside the `godot-steam-audio` folder?

**Comment by ismailivanov** [comment]
> Why is there a `godot-steam-audio` folder inside the `godot-steam-audio` folder?

Ok i reimport the addon now SteamAudioPlauer is playing but i cant hear my voice still
`get_inner_stream_playback` still returning null every frame
demo is working

**Comment by stechyo** [comment]
get_inner_stream_playback returns null but the player returns true on `is_playing()` every frame?

**Comment by ismailivanov** [comment]
> get_inner_stream_playback returns null but the player returns true on `is_playing()` every frame?

yes

**Comment by ismailivanov** [comment]
[steamAudioDemoWithVoiceTest](https://www.mediafire.com/file/xgeb4l0jvj38p1j/godot-steam-audio-demo-v0.2.0.zip/file)

**Comment by stechyo** [comment]
From this demo project it seems like get_inner_stream_playback returns things when called on _process, so, again, assign it on _process(). It seems like Godot doesn't instantiate the playback immediately, so you should wait for get_inner_stream_playback to return a playback before doing anything else.

**Comment by ismailivanov** [comment]
> From this demo project it seems like get_inner_stream_playback returns things when called on _process, so, again, assign it on _process(). It seems like Godot doesn't instantiate the playback immediately, so you should wait for get_inner_stream_playback to return a playback before doing anything else.

Yess now returned and i can hear my voice but still there is problem with voice quality and reverb is always high but i think i can fix this problem myself. Thanks for your help.
