### ISSUE TITLE
Add suport for CSGMeshes.

### ISSUE THREAD

**Issue by ismailivanov** [stechyo/godot-steam-audio#61]
![image](https://github.com/stechyo/godot-steam-audio/assets/64804972/6505c384-718f-4235-a381-c26a787f6d54)
For example i have scene like this and i cant create collisions only with CSGMesh3D but SteamAudioGeometry not support for CSGMesh3D collision.

**Comment by ismailivanov** [comment]
Ok its working with ConcavePolygonShape but i think you must implement CSGMeshes too. I will need CSGMesh support in my procedural dungeon rooms.

**Comment by stechyo** [comment]
There is afaik no way to get a decent set of polygons from CSG meshes, which makes this infeasible. Moreover, from the official Godot [docs](https://docs.godotengine.org/en/stable/tutorials/3d/csg_tools.html): 
> The CSG nodes in Godot are mainly intended for prototyping. There is no built-in support for UV mapping or editing 3D polygons (though extruded 2D polygons can be used with the CSGPolygon3D node).  

CSG nodes are fraught with limitations, and their performance isn't great. You should probably use something else when you're done prototyping.
