### ISSUE TITLE
Crash on adding SteamAudioGeometry with "add_child"

### ISSUE THREAD

**Issue by mrjshzk** [stechyo/godot-steam-audio#62]
**Are you using the provided fork of Godot?**
Yes

**Godot-steam-audio version**
latest

**Steam-Audio version**
latest

**Operating System**
Windows 11

**Describe the bug**
I'm trying to make to write a script that automatically adds SteamAudioGeometry's to my meshInstance3d's nodes. But when calling "add_child" on a SteamAudioGeometry instance, the game just crashes.

```
extends Node3D


# Called when the node enters the scene tree for the first time.
const STEAM_GEOMETRY_MAT = preload("res://addons/godot-steam-audio/materials/default_material.tres")
var meshes : Array[MeshInstance3D] = []
func _enter_tree() -> void:
	get_tree().node_added.connect(
		func(node: Node):
			if node is MeshInstance3D:
				meshes.push_back(node)
	)
	
func _ready() -> void:
	print(meshes)
	for mesh in meshes:
		var s := SteamAudioGeometry.new()
		s.set_material(STEAM_GEOMETRY_MAT)
		print(s)
		mesh.add_child(s) ## calling deferred also crashes
```

**Output:**
![image](https://github.com/stechyo/godot-steam-audio/assets/115943663/25e36e88-8f43-481b-8cce-7a809e02bc19)

**Comment by stechyo** [comment]
I'm afraid I can't reproduce this :/ Could you supply a minimal reproducible project?

**Comment by mrjshzk** [comment]
Hey, I'm sorry. I was actually using my compiled build of godot-steam audio and I think that was it.

But I'm now using the provided addon and editor and I have not been able to bake lightmaps, can you check that?

**Comment by mrjshzk** [comment]
It seems the crash also happens in stock Godot. I'll be closing this issue and sorry for bothering!
