### ISSUE TITLE
Demo project errors upon opening

### ISSUE THREAD

**Issue by bitbutter** [stechyo/godot-steam-audio#63]
**Are you using the provided fork of Godot?**
yes

**Godot-steam-audio version**
0.2.1

**Steam-Audio version**
don't know.

**Operating System**
Windows 10

**Describe the bug**
Upon opening the Demo in the provided Godot build I get errors and SteamAudioPlayer fails to load. 
<img width="1289" alt="image" src="https://github.com/stechyo/godot-steam-audio/assets/52042/d8ee94ed-414a-48e0-bdf4-42082fb1a6db">

Apologies in advance if this is somehow user error.

**Comment by stechyo** [comment]
Hi, not a user error. I had an issue in the Github action that creates the release zips. Please redownload the v0.2.1 release. Sorry for the inconvenience!
