### ISSUE TITLE
No audio and runtime exceptions in the Demo project on Linux

### ISSUE THREAD

**Issue by TibAverus** [stechyo/godot-steam-audio#68]
**Are you using the provided fork of Godot?**
yes

**Godot-steam-audio version**
0.2.1

**Steam-Audio version**
4.5.3

**Operating System**
Manjaro 24.0.6 (64-bit)

**Describe the bug**
Upon opening the demo project with the provided, patched editor, everything seems fine, but as soon as the project is launched, some runtime exceptions come up (See Example screenshots), and no audio can be heard at all.

**To Reproduce**
1. Download the patched version of godot 4.3
2. Download godot-steam-audio from the releases tab, with the demo included
3. Open the project and run.

**Expected behavior**
Audio should be working with no runtime exceptions

**Example project, code snippet, or screenshots**
![image](https://github.com/user-attachments/assets/ab4e780b-6ff8-4191-b9fe-93ccadf0e17f)

**Comment by stechyo** [comment]
The current release is incompatible with 4.3, I’ve only released that patched 4.3 because I’m testing a compatible version of the extension. What happens with [this version](https://github.com/stechyo/godot-steam-audio/actions/runs/10467092716/artifacts/1831155475)?

**Comment by TibAverus** [comment]
I tried my best to collect the latest things from the 4.3 branch, so I assumed that's the patched version which needs testing to see if it still crashes.

The version provided above had a typo in one of the .so file names
![image](https://github.com/user-attachments/assets/0900c4a4-06f2-40cc-83fd-bb9d23c41188)

Renaming ```libgodot-steam-audio.linux.template_debug.x86_64.so```
to ```libgodot-steam-audio.linux.template_debug.dev.x86_64.so```
solves the issue and the project works.

**Comment by stechyo** [comment]
Hm, that should be fixed in the latest prerelease run ([here](https://github.com/stechyo/godot-steam-audio/actions/runs/10537218694/artifacts/1850071947)), gonna merge it in a bit. Thank you for testing!
