### ISSUE TITLE
Add Godot 4.3 .NET export version.

### ISSUE THREAD

**Issue by ismailivanov** [stechyo/godot-steam-audio#69]
**Some plugins require C# to use, and this is currently impossible when using Steam Audio.**

**Comment by stechyo** [comment]
[Release](https://github.com/stechyo/godot/releases/tag/4.3-steam-audio) updated, can you check if the mono editor works on windows?

**Comment by ismailivanov** [comment]
> [Release](https://github.com/stechyo/godot/releases/tag/4.3-steam-audio) updated, can you check if the mono editor works on windows?

Im Using Linux :)

**Comment by stechyo** [comment]
No worries :) does the linux version work with the plugins you’re looking to use?

**Comment by ismailivanov** [comment]
> No worries :) does the linux version work with the plugins you’re looking to use?

I will try when I get home

**Comment by ismailivanov** [comment]
> No worries :) does the linux version work with the plugins you’re looking to use?

Thanks, it worked.
