### ISSUE TITLE
turning off occlusion on SteamAudioPlayer makes the sound not play correctly

### ISSUE THREAD

**Issue by bypell** [stechyo/godot-steam-audio#70]
**Are you using the provided fork of Godot?**
yes

**Godot-steam-audio version**
0.2.2

**Steam-Audio version**
4.5.3 (probably)

**Operating System**
windows 10/11

**Describe the bug**
turning off occlusion on a SteamAudioPlayer leads to a kind of screeching noise, similar to the noise you hear when an app with audio starts freezing. 

**To Reproduce**
1. add SteamAudioPlayer to scene
2. add audio stream
3. turn off occlusion
4. make it play at runtime
5. run the project

**Expected behavior**
my ears not bleeding :( and being able to disable occlusion without weird behavior

**Example project, code snippet, or screenshots**
If applicable, add some examples to help explain your problem.

**Additional context**
Haven't seen anyone mention this in the issues, been doing workarounds for a while but it doesn't seem like people are running into this problem which leads me to believe this is a me problem, even though I've never been able to successfully turn off occlusion no matter the project.

**Comment by stechyo** [comment]
Can you check #71's release build? ([Link](https://github.com/stechyo/godot-steam-audio/actions/runs/10971259636/artifacts/1961395330)) I tested it and it should be fixed.

**Comment by bypell** [comment]
Sorry for the late response. Tried it in a simple project and it seems to work! Thanks!
I guess I can close this
