### ISSUE TITLE
No Audio from SteamAudioPlayers on Game Export (to Windows Desktop)

### ISSUE THREAD

**Issue by niefia** [stechyo/godot-steam-audio#72]
**Are you using the provided fork of Godot?**
Yes (Fork of Godot 4.2.2)

**Godot-steam-audio version**
0.2.1

**Steam-Audio version**
version included with - Godot-steam-audio version 0.2.1

**Operating System**
Windows 10

**Describe the bug**
No Audio from SteamAudioPlayers on Game Export (to Windows Desktop)

SteamAudioPlayers are working fine inside Godot editor.

Regular AudioStreamPlayer3D work fine, so not an issue with export game audio overall

**To Reproduce**
1. Using the demo here: [godot-steam-audio-demo-v0.2.1.zip](https://github.com/stechyo/godot-steam-audio/releases/download/0.2.1/godot-steam-audio-demo-v0.2.1.zip) and [Steam audio Godot Fork 4.2.2 ](https://github.com/stechyo/godot/tree/4.2.2-stable-steam-audio)
2. Project -> Export -> Windows Desktop (Runnable), with default Godot settings
3. Launch Exported .exe

**Expected behavior**
SteamAudioPlayers work the same in Export as in Editor

**Additional context**
Console on export:
![image](https://github.com/user-attachments/assets/45977c87-27ea-4329-a7e3-7f9d5f1b774a)

**Comment by stechyo** [comment]
Just to check, are you using the release templates found in the [fork release](https://github.com/stechyo/godot/releases/tag/4.2.2-stable-steam-audio)? These errors happen when the official release templates are used, hence the question.

**Comment by niefia** [comment]
Specifically using `godot.windows.editor.x86_64.exe` from that [link](https://github.com/stechyo/godot/releases/tag/4.2.2-stable-steam-audio).

And using a copy of the [demo ](https://github.com/stechyo/godot-steam-audio/releases/download/0.2.1/godot-steam-audio-demo-v0.2.1.zip) which I'm opening with that version of the editor (but have the same issue with my project on export)

Everything works fine in the Editor so don't think it's an issue of using the official Godot fork instead of the Steam Audio Godot fork. 

Attached a video to demonstrate it working in Editor, but not on export, just in case there's something I'm missing:


https://github.com/user-attachments/assets/ea040576-1559-4177-9185-51889fd07b8f

**Comment by stechyo** [comment]
When you’re exporting your game you need to use the specific templates (template_debug, template_release) from that release as well. It seems like you’re using the official templates, which won’t work (correct me if I’m wrong ofc). Check this page in the wiki: https://github.com/stechyo/godot-steam-audio/wiki/Exporting-your-game

**Comment by niefia** [comment]
Solved, was just my mistake
