### ISSUE TITLE
is the custom fork still needed

### ISSUE THREAD

**Issue by octanejohn** [stechyo/godot-steam-audio#78]
godot 4.4 dev 4 has your fixes

https://godotengine.org/article/dev-snapshot-godot-4-4-dev-4/

**Comment by stechyo** [comment]
Thanks for the headsup! Been looking into it, seems there are some things that changed in the godot-cpp generated headers.

**Comment by stechyo** [comment]
Closing, there's a prerelease in #79. It's not compatible with 4.3 so I'll merge this PR when 4.4-stable comes out.
