### ISSUE TITLE
Audio distortion/noise/feedback issue

### ISSUE THREAD

**Issue by TheIndiv** [stechyo/godot-steam-audio#80]
**Are you using the provided fork of Godot?**
Yes

**Godot-steam-audio version**
0.2.2

**Steam-Audio version**
Unsure. Whichever is in the 0.2.2 release

**Operating System**
Windows 11

**Describe the bug**
Audio distortion/noise/feedback issue.

**To Reproduce**
1. Add a new SteamAudioPlayer
2. Add a stream (I used the 2.mp3 file from the demo)
3. Turn off Occlusion and turn on Autoplay
4. Play the scene

**Expected behavior**
Normal audio

**Example project, code snippet, or screenshots**
VOLUME WARNING
[[Video link]](https://cdn.discordapp.com/attachments/1230669303775498395/1315389701548675172/Untitled_video_-_Made_with_Clipchamp.mp4?ex=67573b9f&is=6755ea1f&hm=673d525a2b05e44bbb913ac8aaf9aee52f604ba22b708c21bf4f685bc4aed3c1&)

**Additional context**
If you turn occlusion back on then the problem seems to fix itself?

**Comment by stechyo** [comment]
This is likely a duplicate of #70, I'll make a new release later today if I have the time.

**Comment by stechyo** [comment]
Please check [0.2.3](https://github.com/stechyo/godot-steam-audio/releases/tag/0.2.3) to see if it fixes this, and close the issue if it does. Thanks!

**Comment by TheIndiv** [comment]
Sorry about the delay in testing.
The issue seems to be solved!
Closed.
